/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.wwjjbb.RfKillManager.xml -a rfkilladaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef RFKILLADAPTOR_H
#define RFKILLADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.wwjjbb.RfKillManager
 */
class RfKillManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.wwjjbb.RfKillManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.wwjjbb.RfKillManager\">\n"
"    <signal name=\"statusChanged\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"status\"/>\n"
"    </signal>\n"
"    <method name=\"setStatus\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"requestStatus\"/>\n"
"  </interface>\n"
        "")
public:
    RfKillManagerAdaptor(QObject *parent);
    virtual ~RfKillManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void requestStatus();
    void setStatus(bool status);
Q_SIGNALS: // SIGNALS
    void statusChanged(bool status);
};

#endif
